[tool.commitizen]
name = "cz_conventional_commits"
# version_provider = "poetry"
tag_format = "v$version"
version_scheme = "semver"
version = "0.5.1"
update_changelog_on_bump = true
major_version_zero = true
bump_message = "BUMP: version $current_version → $new_version"
commit_url = "https://github.com/MetalBrackets/AutoChangelogMainPush/commit/$COMMIT_REV"

