name: Generate Changelog

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Changelog
        # uses: seasonalmatcha/conventional-commit-changelog@v1.0.0  # Utiliser une version spécifique si possible
      - uses: seasonalmatcha/conventional-commit-changelog@latest
        id: changelog
        with:
          from: v1.0.0
          to: v2.0.0

      - name: Upload Changelog
        run: |
          # Ajoutez ici les commandes nécessaires pour publier ou enregistrer le changelog
          # Par exemple, copier le changelog généré dans un fichier et l'ajouter à une release
          echo "Changelog generated"
