on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Bump version

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4

        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          release-type: simple
          # optional. customize path to release-please-config.json
          # config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          # manifest-file: .release-please-manifest.json
