# name: Bump version

# on:
#   push:
#     branches:
#       - main

# jobs:
#   bump-version:
#     if: "!startsWith(github.event.head_commit.message, 'bump:')"
#     runs-on: ubuntu-latest
#     name: "Bump version and create changelog with commitizen"
#     steps:
#       - name: Check out
#         uses: actions/checkout@v3
#         with:
#           token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
#           fetch-depth: 0
#       - name: Create bump and changelog
#         uses: commitizen-tools/commitizen-action@master
#         with:
#           github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


#           


name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0 

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'

      # - name: Install Commitizen
      #   run: pip install commitizen

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Display commit URL
        run: |
          echo "Voir le commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}"


      - name: Push changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git push origin HEAD:main --tags
